//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.07 at 11:47:18 AM CEST 
//


package iristk.xml.event;

import java.util.ArrayList;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for recordType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="recordType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;group ref="{iristk.event}value"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "recordType", propOrder = {
    "recordOrListOrString"
})
@XmlSeeAlso({
    Event.class,
    Record.class,
    iristk.xml.event.List.class
})
public class RecordType {

    @XmlElements({
        @XmlElement(name = "record", type = Record.class),
        @XmlElement(name = "list", type = iristk.xml.event.List.class),
        @XmlElement(name = "string", type = String.class),
        @XmlElement(name = "float", type = Float.class),
        @XmlElement(name = "int", type = Int.class),
        @XmlElement(name = "bool", type = Bool.class),
        @XmlElement(name = "xml", type = Xml.class)
    })
    protected java.util.List<Object> recordOrListOrString;

    /**
     * Gets the value of the recordOrListOrString property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the recordOrListOrString property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRecordOrListOrString().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Record }
     * {@link iristk.xml.event.List }
     * {@link String }
     * {@link Float }
     * {@link Int }
     * {@link Bool }
     * {@link Xml }
     * 
     * 
     */
    public java.util.List<Object> getRecordOrListOrString() {
        if (recordOrListOrString == null) {
            recordOrListOrString = new ArrayList<Object>();
        }
        return this.recordOrListOrString;
    }

}
