//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.18 at 02:26:56 PM CET 
//


package iristk.xml.flow;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the iristk.xml.flow package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: iristk.xml.flow
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Flow }
     * 
     */
    public Flow createFlow() {
        return new Flow();
    }

    /**
     * Create an instance of {@link ActionTemplate }
     * 
     */
    public ActionTemplate createActionTemplate() {
        return new ActionTemplate();
    }

    /**
     * Create an instance of {@link Param }
     * 
     */
    public Param createParam() {
        return new Param();
    }

    /**
     * Create an instance of {@link Goto }
     * 
     */
    public Goto createGoto() {
        return new Goto();
    }

    /**
     * Create an instance of {@link Call }
     * 
     */
    public Call createCall() {
        return new Call();
    }

    /**
     * Create an instance of {@link Return }
     * 
     */
    public Return createReturn() {
        return new Return();
    }

    /**
     * Create an instance of {@link If }
     * 
     */
    public If createIf() {
        return new If();
    }

    /**
     * Create an instance of {@link ActionSequenceType }
     * 
     */
    public ActionSequenceType createActionSequenceType() {
        return new ActionSequenceType();
    }

    /**
     * Create an instance of {@link Elseif }
     * 
     */
    public Elseif createElseif() {
        return new Elseif();
    }

    /**
     * Create an instance of {@link Else }
     * 
     */
    public Else createElse() {
        return new Else();
    }

    /**
     * Create an instance of {@link Random }
     * 
     */
    public Random createRandom() {
        return new Random();
    }

    /**
     * Create an instance of {@link Raise }
     * 
     */
    public Raise createRaise() {
        return new Raise();
    }

    /**
     * Create an instance of {@link Send }
     * 
     */
    public Send createSend() {
        return new Send();
    }

    /**
     * Create an instance of {@link Wait }
     * 
     */
    public Wait createWait() {
        return new Wait();
    }

    /**
     * Create an instance of {@link Block }
     * 
     */
    public Block createBlock() {
        return new Block();
    }

    /**
     * Create an instance of {@link Exec }
     * 
     */
    public Exec createExec() {
        return new Exec();
    }

    /**
     * Create an instance of {@link Var }
     * 
     */
    public Var createVar() {
        return new Var();
    }

    /**
     * Create an instance of {@link Log }
     * 
     */
    public Log createLog() {
        return new Log();
    }

    /**
     * Create an instance of {@link Reentry }
     * 
     */
    public Reentry createReentry() {
        return new Reentry();
    }

    /**
     * Create an instance of {@link Propagate }
     * 
     */
    public Propagate createPropagate() {
        return new Propagate();
    }

    /**
     * Create an instance of {@link OnEntry }
     * 
     */
    public OnEntry createOnEntry() {
        return new OnEntry();
    }

    /**
     * Create an instance of {@link Choice }
     * 
     */
    public Choice createChoice() {
        return new Choice();
    }

    /**
     * Create an instance of {@link Item }
     * 
     */
    public Item createItem() {
        return new Item();
    }

    /**
     * Create an instance of {@link State }
     * 
     */
    public State createState() {
        return new State();
    }

    /**
     * Create an instance of {@link OnEvent }
     * 
     */
    public OnEvent createOnEvent() {
        return new OnEvent();
    }

    /**
     * Create an instance of {@link OnExit }
     * 
     */
    public OnExit createOnExit() {
        return new OnExit();
    }

    /**
     * Create an instance of {@link Expr }
     * 
     */
    public Expr createExpr() {
        return new Expr();
    }

    /**
     * Create an instance of {@link Flow.Import }
     * 
     */
    public Flow.Import createFlowImport() {
        return new Flow.Import();
    }

    /**
     * Create an instance of {@link Include }
     * 
     */
    public Include createInclude() {
        return new Include();
    }

    /**
     * Create an instance of {@link Flow.Init }
     * 
     */
    public Flow.Init createFlowInit() {
        return new Flow.Init();
    }

    /**
     * Create an instance of {@link CatchTemplate }
     * 
     */
    public CatchTemplate createCatchTemplate() {
        return new CatchTemplate();
    }

    /**
     * Create an instance of {@link IfType }
     * 
     */
    public IfType createIfType() {
        return new IfType();
    }

}
