// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package iristk.speech.windows;

@net.sf.jni4net.attributes.ClrType
public class Hypothesis extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected Hypothesis(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("()V")
    public Hypothesis() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        iristk.speech.windows.Hypothesis.__ctorHypothesis0(this);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    private native static void __ctorHypothesis0(net.sf.jni4net.inj.IClrProxy thiz);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getText();
    
    @net.sf.jni4net.attributes.ClrMethod("()F")
    public native float getConfidence();
    
    @net.sf.jni4net.attributes.ClrMethod("()I")
    public native int size();
    
    @net.sf.jni4net.attributes.ClrMethod("()Liristk/speech/windows/SemanticStruct;")
    public native iristk.speech.windows.SemanticStruct getSemantics();
    
    @net.sf.jni4net.attributes.ClrMethod("(I)Liristk/speech/windows/Word;")
    public native iristk.speech.windows.Word getWord(int index);
    
    public static system.Type typeof() {
        return iristk.speech.windows.Hypothesis.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        iristk.speech.windows.Hypothesis.staticType = staticType;
    }
    //</generated-proxy>
}
