// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package iristk.speech.windows;

@net.sf.jni4net.attributes.ClrTypeInfo
public final class IResultListener_ {
    
    //<generated-static>
    private static system.Type staticType;
    
    public static system.Type typeof() {
        return iristk.speech.windows.IResultListener_.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        iristk.speech.windows.IResultListener_.staticType = staticType;
    }
    //</generated-static>
}

//<generated-proxy>
@net.sf.jni4net.attributes.ClrProxy
class __IResultListener extends system.Object implements iristk.speech.windows.IResultListener {
    
    protected __IResultListener(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("(I)V")
    public native void speechDetected(int audioLevel);
    
    @net.sf.jni4net.attributes.ClrMethod("(Liristk/speech/windows/Result;)V")
    public native void recognizeCompleted(iristk.speech.windows.Result result);
    
    @net.sf.jni4net.attributes.ClrMethod("(Liristk/speech/windows/Result;)V")
    public native void recognizeHypothesis(iristk.speech.windows.Result result);
}
//</generated-proxy>
