// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package iristk.speech.windows;

@net.sf.jni4net.attributes.ClrInterface
public interface IResultListener {
    
    //<generated-interface>
    @net.sf.jni4net.attributes.ClrMethod("(I)V")
    void speechDetected(int audioLevel);
    
    @net.sf.jni4net.attributes.ClrMethod("(Liristk/speech/windows/Result;)V")
    void recognizeCompleted(iristk.speech.windows.Result result);
    
    @net.sf.jni4net.attributes.ClrMethod("(Liristk/speech/windows/Result;)V")
    void recognizeHypothesis(iristk.speech.windows.Result result);
    //</generated-interface>
}
