// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package iristk.speech.windows;

@net.sf.jni4net.attributes.ClrType
public class ManagedSynthesizer extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected ManagedSynthesizer(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("()V")
    public ManagedSynthesizer() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        iristk.speech.windows.ManagedSynthesizer.__ctorManagedSynthesizer0(this);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    private native static void __ctorManagedSynthesizer0(net.sf.jni4net.inj.IClrProxy thiz);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setVoice(java.lang.String name);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;LSystem/String;)Liristk/speech/windows/Phonemes;")
    public native iristk.speech.windows.Phonemes synthesize(java.lang.String ssml, java.lang.String path);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)Liristk/speech/windows/Phonemes;")
    public native iristk.speech.windows.Phonemes transcribe(java.lang.String ssml);
    
    @net.sf.jni4net.attributes.ClrMethod("()Liristk/speech/windows/Voices;")
    public native iristk.speech.windows.Voices getVoices();
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native void printVoices();
    
    public static system.Type typeof() {
        return iristk.speech.windows.ManagedSynthesizer.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        iristk.speech.windows.ManagedSynthesizer.staticType = staticType;
    }
    //</generated-proxy>
}
