// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package iristk.speech.windows;

@net.sf.jni4net.attributes.ClrType
public class ManagedRecognizer extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected ManagedRecognizer(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("()V")
    public ManagedRecognizer() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        iristk.speech.windows.ManagedRecognizer.__ctorManagedRecognizer0(this);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    private native static void __ctorManagedRecognizer0(net.sf.jni4net.inj.IClrProxy thiz);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)I")
    public native int getRecognizerSetting(java.lang.String name);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;I)V")
    public native void setRecognizerSetting(java.lang.String name, int value);
    
    @net.sf.jni4net.attributes.ClrMethod("(I)V")
    public native void setMaxAlternates(int max);
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native void startRecognizing();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void saveAudio(java.lang.String folderPath);
    
    @net.sf.jni4net.attributes.ClrMethod("(Liristk/speech/windows/IResultListener;)V")
    public native void registerListener(iristk.speech.windows.IResultListener listener);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void init(java.lang.String lang);
    
    @net.sf.jni4net.attributes.ClrMethod("()I")
    public native int getAudioLevel();
    
    @net.sf.jni4net.attributes.ClrMethod("(II)V")
    public native void setInputToAudioStream(int sampleRate, int bufferSize);
    
    @net.sf.jni4net.attributes.ClrMethod("()Liristk/speech/windows/SpeechAudioStream;")
    public native iristk.speech.windows.SpeechAudioStream getAudioStream();
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native void setInputToDefaultAudioDevice();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setInputToWaveFile(java.lang.String path);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void deactivateGrammar(java.lang.String name);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;F)V")
    public native void activateGrammar(java.lang.String name, float weight);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void activateGrammar(java.lang.String name);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void loadDictationGrammar(java.lang.String name);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;LSystem/String;)V")
    public native void loadGrammarFromPath(java.lang.String name, java.lang.String path);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;LSystem/String;)V")
    public native void loadGrammarFromString(java.lang.String name, java.lang.String grammar);
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native void recognizeCancel();
    
    @net.sf.jni4net.attributes.ClrMethod("(I)V")
    public native void setNoSpeechTimeout(int msec);
    
    @net.sf.jni4net.attributes.ClrMethod("(I)V")
    public native void setEndSilTimeout(int msec);
    
    @net.sf.jni4net.attributes.ClrMethod("(I)V")
    public native void setMaxSpeechTimeout(int msec);
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native void recognize();
    
    public static system.Type typeof() {
        return iristk.speech.windows.ManagedRecognizer.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        iristk.speech.windows.ManagedRecognizer.staticType = staticType;
    }
    //</generated-proxy>
}
