// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package iristk.speech.windows;

@net.sf.jni4net.attributes.ClrType
public class SemanticStruct extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected SemanticStruct(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("()V")
    public SemanticStruct() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        iristk.speech.windows.SemanticStruct.__ctorSemanticStruct0(this);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    private native static void __ctorSemanticStruct0(net.sf.jni4net.inj.IClrProxy thiz);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Object;")
    public native system.Object getValue();
    
    @net.sf.jni4net.attributes.ClrMethod("()F")
    public native float getConfidence();
    
    @net.sf.jni4net.attributes.ClrMethod("()I")
    public native int getKeysCount();
    
    @net.sf.jni4net.attributes.ClrMethod("(I)LSystem/String;")
    public native java.lang.String getKey(int i);
    
    @net.sf.jni4net.attributes.ClrMethod("(I)Liristk/speech/windows/SemanticStruct;")
    public native iristk.speech.windows.SemanticStruct getValue(int i);
    
    public static system.Type typeof() {
        return iristk.speech.windows.SemanticStruct.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        iristk.speech.windows.SemanticStruct.staticType = staticType;
    }
    //</generated-proxy>
}
