// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package iristk.speech.windows;

@net.sf.jni4net.attributes.ClrType
public class SpeechAudioStream extends system.io.Stream {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected SpeechAudioStream(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("(I)V")
    public SpeechAudioStream(int bufferSize) {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        iristk.speech.windows.SpeechAudioStream.__ctorSpeechAudioStream0(this, bufferSize);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("(I)V")
    private native static void __ctorSpeechAudioStream0(net.sf.jni4net.inj.IClrProxy thiz, int bufferSize);
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native void Clear();
    
    public static system.Type typeof() {
        return iristk.speech.windows.SpeechAudioStream.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        iristk.speech.windows.SpeechAudioStream.staticType = staticType;
    }
    //</generated-proxy>
}
